### ISSUE TITLE
New Messages does not appear in the char room after sometime of chatting

### ISSUE THREAD

**Issue by abhinavkrin** [Kushagraw12/React-Chat-App#8]
After chatting for some time, when I tried to send messages, the messages are sent but they don't appear in the chat list.
This occurs because of the wrong ordering of chat messages while reading from the database.

**Comment by abhinavkrin** [comment]
@Kushagraw12 can you assign me this issue.

**Comment by Kushagraw12** [comment]
@abhinavkrin Can we please text over discord?
I am facing some issues while running it locally, majorly when I add my own firebase config.  
Here is my discord username:
Kushagra Wadhwa#5067

Thanks a lot!!

**Comment by abhinavkrin** [comment]
Sure, I am messaging you.

**Comment by abhinavkrin** [comment]
Received a request from null#8964 ?

**Comment by Kushagraw12** [comment]
Resolved
